mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^polls/',include('polls.urls')),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns=[
    #/polls/
    url(r'^$',views.index,name="index"),
    #/polls/5
    url(r'^(?P<question_id>[0-9]+)/$',views.detail,name="detail"),
    #/polls/5/detail/
    url(r'^(?P<question_id>[0-9]+)/results/$',views.results,name='results'),
    #polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
]

mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date= models.DateTimeField('date published')

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete= models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question,Choice
from django.http import Http404
from django.urls import reverse

#import thu vien de su dung template
from django.template import loader
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    #dung phuong thuc de su dung template
    #template = loader.get_template('polls/index.html')
    #bien truyen vao template
    context={'latest_question_list': latest_question_list}
    return render(request,'polls/index.html',context)
    #ngoai ra co the su dung render
    #from django.shortcuts import render
 
# Create your views here.
app_name ="polls"
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:        
        raise Http404("Question does not exist")
    return render(request,'polls/detail.html',{'question':question})
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id) 
    return render(request, 'polls/results.html', {'question': question})

def vote(request,question_id):
    #ham chay try giai phong loi 404 neu co
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set_get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',{'question':question,'error_message':"You didn't select a choice",})
    else:
        selected_choice.vote +=1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))

mysite/polls/templates/polls/detail.html
<h1>{{question.question_text}}</h1>
{% if error_message %}
<strong>{{error_message}}</strong>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.count }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.count }}">{{ choice.choice_text}}</label>
    {% endfor %}
    <input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available</p>
{% endif %}    

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
 
<ul>
    {% for choice in question.choice_set.all %}
    <li>
    {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes | pluralize }}
    </li>
    {% endfor %}
</ul>
 
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>